import { Button } from '@/components/ui/button'
import { Github } from 'lucide-react'
import { Separator } from './components/ui/separator'
import { Textarea } from './components/ui/textarea'

export function App() {
  return (
    <div className="min-h-screen flex flex-col">
      <header className="px-6 py-3 flex items-center justify-between border-b">
        <h1 className="text-xl font-bold">upload.ai</h1>
        <div className="flex items-center gap-3">
          <span className="text-sm text-muted-foreground">
            Developed by @dwtoledo on Rocketseat NLW
          </span>

          <Separator orientation="vertical" className="h-6" />
          <Button variant="outline">
            <Github className="w-4 h-4 mr-2" />
            GitHub
          </Button>
        </div>
      </header>
      <main className="flex-1 p-6 flex gap-6">
        <div className="flex flex-col flex-1 gap-4">
          <div className="grid grid-rows-2 gap-4 flex-1">
            <Textarea
              placeholder="Include the prompt for the AI..."
              className="resize-none p-4 leading-relaxed"
            ></Textarea>
            <Textarea
              placeholder="Result generated by AI..."
              className="resize-none p-4 leading-relaxed"
              readOnly
            ></Textarea>
          </div>
          <p className="text-sm text-muted-foreground">
            Remember: You can use the variable{' '}
            <code className="text-violet-400">{'{transcription}'}</code> in your
            prompt to add the selected video transcription.
          </p>
        </div>
        <aside className="w-80"></aside>
      </main>
    </div>
  )
}
